[build]
builder = "NIXPACKS"
buildCommand = "cd /app && mkdir -p apps/web/src/__generated__ && corepack enable && corepack pnpm install --frozen-lockfile --workspace-root && corepack pnpm relay && corepack pnpm --filter @woovi-playground/web build"

[deploy]
startCommand = "cd /app && NODE_ENV=production PORT=3000 pnpm --filter @woovi-playground/web start"
restartPolicyType = "ON_FAILURE"