[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm relay && pnpm build"

[deploy]
startCommand = "node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"