[build]
builder = "NIXPACKS"
buildCommand = "cd apps/server && pnpm install --frozen-lockfile && pnpm build"

[deploy]
startCommand = "cd apps/server && node dist/index.js"
restartPolicyType = "ON_FAILURE"